### ISSUE TITLE
Problemas de conectividade com alto volume

### ISSUE THREAD

**Issue by tkrafael** [matheuspilger/RabbitMQApp#1]
https://github.com/matheuspilger/RabbitMQApp/blob/e7fde525db5baca362b70eb92c756216a47644ea/RabbitMQApp.Domain/Services/CreateMessageService.cs#L29

O que aconteceria em cenários com alto volume? 
Na minha análise, teríamos centenas de conexões abrindo e fechando para cada envio.
Esse cenário descreve o que aconteceria: https://docs.appdynamics.com/appd/22.x/22.5/en/infrastructure-visibility/network-visibility/workflows-and-example-use-cases/tcp-port-exhaustion-example-use-case

Nesse caso, qual seria a metodologia pra resolver esse problema?

**Comment by matheuspilger** [comment]
> https://github.com/matheuspilger/RabbitMQApp/blob/e7fde525db5baca362b70eb92c756216a47644ea/RabbitMQApp.Domain/Services/CreateMessageService.cs#L29
> 
> O que aconteceria em cenários com alto volume? Na minha análise, tivemos centenas de conexões abrindo e fechando para cada envio. Esse cenário descreve o que aconteceria: [https://docs.appdynamics.com/appd/22.x/22.5/en/infrastructure-visibility/network-visibility/workflows-and-example-use-cases/tcp-port-exhaustion -exemplo-caso de uso](https://docs.appdynamics.com/appd/22.x/22.5/en/infrastructure-visibility/network-visibility/workflows-and-example-use-cases/tcp-port-exhaustion-example-use-case)
> 
> Nesse caso, qual seria a metodologia para resolver esse problema?

Para resolver essa situação de abrir varias Conexões cada vez que envia uma mensagem, poderíamos criar uma classe onde ela seria responsável por criar a conexão  e depois adicionarmos como Singleton na injeção de dependência.

Nesse caso, quando instanciarmos o CreateMessageService a injeção ira resolver sempre a mesma instância da conexão.
