### ISSUE TITLE
Sync over async

### ISSUE THREAD

**Issue by tkrafael** [matheuspilger/RabbitMQApp#2]
https://github.com/matheuspilger/RabbitMQApp/blob/e7fde525db5baca362b70eb92c756216a47644ea/RabbitMQApp.Domain/Handlers/CreateMessageHandler.cs#L20

Gostaria de entender qual é a intenção de encapsular um método síncrono dentro de um `Task.Run`

Sabemos que isso pode ter implicações negativas no desempenho. Caso tenha conhecimento sobre, pode detalhar?

**Comment by matheuspilger** [comment]
https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequestHandler.cs

Nesse caso eu decidi usar o Mediator e o mesmo implementa uma interface com o seguinte método Task Handle(TRequest request, CancellationToken cancellationToken) por isso usei o Task.Run;

Mas na questão de desempenho, realmente poderia ter feito de maneira diferente, sem encapsular o Publish, porque da maneira que está seria bem menos performático colocar pra executar em outra Thread, quando tivesse uma massa gigante de dados iria apresentar problemas de performance.
